### ISSUE TITLE
ModuleNotFoundError: No module named 'threestudio.models.geometry.gaussian_base'

### ISSUE THREAD

**Issue by KhoiDOO** [2y7c3/ASD#6]
Hi, thank you for a good repo. I was trying to generate a 3D sample by the following command
```
python launch.py --config configs/test_nerf.yaml --train --gpu 0 system.prompt_processor.prompt="A delicious hamburger"
```
However, I caught this error
```
/media/mountHDD1/users/luffy/3ddiverse/threestudio/utils/ops.py:45: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/utils/ops.py:52: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, g):  # pylint: disable=arguments-differ
/media/mountHDD1/users/luffy/3ddiverse/threestudio/utils/ops.py:62: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input_tensor, gt_grad):
/media/mountHDD1/users/luffy/3ddiverse/threestudio/utils/ops.py:69: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_scale):
/media/mountHDD1/users/luffy/.env/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/media/mountHDD1/users/luffy/.env/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/deep_floyd_guidance.py:107: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/deep_floyd_guidance.py:112: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/deep_floyd_guidance.py:281: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/deep_floyd_guidance.py:336: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:140: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:145: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:159: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:169: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:450: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_guidance.py:503: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:155: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:160: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:186: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:196: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:601: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_controlnet_guidance.py:659: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:344: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:349: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:378: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:397: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:407: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/guidance/stable_diffusion_asd_guidance.py:928: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
Traceback (most recent call last):
  File "/media/mountHDD1/users/luffy/3ddiverse/launch.py", line 241, in <module>
    main(args, extras)
  File "/media/mountHDD1/users/luffy/3ddiverse/launch.py", line 74, in main
    import threestudio
  File "/media/mountHDD1/users/luffy/3ddiverse/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/__init__.py", line 1, in <module>
    from . import (
  File "/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/renderers/__init__.py", line 1, in <module>
    from . import (
  File "/media/mountHDD1/users/luffy/3ddiverse/threestudio/models/renderers/gs_renderer.py", line 4, in <module>
    from ..geometry.gaussian_base import BasicPointCloud, Camera
ModuleNotFoundError: No module named 'threestudio.models.geometry.gaussian_base'
```

From my perspective is that a problem of missing file, that's because I did see no gaussian_base in the geometry folder.

Thank you

**Comment by 2y7c3** [comment]
Sorry, we did not completely clean up the 3DGS-related code when we released the NeRF-related code. Now we released the training codes for 3DGS，you could try it again.

**Comment by KhoiDOO** [comment]
Thank you so much, I will try and report if there exist any error

**Comment by KhoiDOO** [comment]
I will close this issue here cause it works
